import math
def get_objects():
  data = [12, 
          1.2, 
          4j,
          '123', 
          reversed('123'), 
          filter(None, '123'), 
          map('123', '321'), 
          memoryview(b'123'), 
          enumerate(b'123'), 
          iter('123'), 
          slice('123'), 
          range(4,5), 
          (x for x in range(1,2)), 
          list(), 
          dict(), 
          tuple(), 
          set(), 
          type, 
          True, 
          None,
          iter([]), 
          iter({}),
          iter(set()), 
          dir, 
          zip(),
          bytes(), 
          bytearray(), 
          frozenset(), 
          property(), 
          object(), 
          ValueError(), 
          NameError(), 
          TypeError(), 
          GeneratorExit(), 
          FutureWarning(), 
          FloatingPointError(), 
          FileNotFoundError(), 
          FileExistsError(), 
          Exception(), 
          EOFError(), 
          EnvironmentError(), 
          DeprecationWarning(), 
          staticmethod(None), 
          classmethod(None), 
          get_objects,
          math, 
          str.title]
  data_types = sorted(data, key = lambda x: str(type(x)))
  return data_types